### ISSUE TITLE
Toolchain configuration

### ISSUE THREAD

**Issue by towoe** [tock/libtock-c#114]
Is there a reason why the `TOOLCHAIN_*` variables are set with the `override` prefix in `Configuration.mk`?

The values for `TOOLCHAIN_rv32im[a]c` are currently `riscv64-unknown-elf`.
Some packages (e.g. Arch, which is also referenced in the README.md) have binaries which have a prefix `riscv64-elf`.
It should also be possible to compile with `riscv32-unknown-elf-gcc`.
Not using `override` would help to configure which compiler is used locally.

The configuration dump of `Configuration.mk` uses the variable `TOOLCHAIN` but as far as I can see it is never used, to this output is a bit confusing.

**Comment by ppannuto** [comment]
`override` is necessary for the FLAGS variables and several other configuration ones -- it was probably a bit of an overzealous pass of adding override to everything at some point in the past. I don't think there's a specific need for TOOLCHAIN to be override.

Ideally, we'd probably do a pass and leave override for everything with a `+=` directive and drop it for all the `:=` 's

**Comment by towoe** [comment]
Thanks for the quick reply @ppannuto and explanation!
I removed the keyword in the PR, if there are more changes you would like me to add to the PR feel free to comment.
