### ISSUE TITLE
Remove lua runtime

### ISSUE THREAD

**Issue by brghena** [tock/libtock-c#2]
If we're separating out language-specific runtimes into their own repos, this repo shouldn't include Lua support.

**Comment by bradjc** [comment]
Lua support is based on a substantial C library. Does it makes sense to have a copy of the c build system to compile the Lua interpreter in a different repo?

I agree that if we had pure Lua examples those should be in a separate repo.

**Comment by brghena** [comment]
Oh, I had forgotten that it was using the raw C libraries. I guess that's fine then. Still a bit confusing to have in the C repo, but an infinitely better option than copying code into a second repo.
