### ISSUE TITLE
tockloader install --board opentitan/earlgrey-nexysvideo issues

### ISSUE THREAD

**Issue by nicolast0604** [tock/libtock-c#266]
Hi I am very new to tock and encounter the problems which is confused.
Could you please give me hint what's wrong with it?

$tockloader install --board opentitan/earlgrey-nexysvideo --openocd blink/build/blink.tab
[ERROR  ] Unknown OpenOCD board name. You must pass --openocd-board.
$tockloader install --board opentitan/earlgrey-nexysvideo --openocd-earlgrey-nexysvideo blink/build/blink.tab
[WARNING] Unknown arguments passed. You may need to update tockloader.
[WARNING] Unknown argument "--openocd-earlgrey-nexysvideo"
[INFO   ] No device name specified. Using default name "tock".
[INFO   ] No serial port with device name "tock" found.
[INFO   ] Found 1 serial port.
[INFO   ] Using "/dev/ttyUSB0 - FT232R USB UART - FT232R USB UART".
[STATUS ] Installing app on the board...
[ERROR  ] Error connecting to bootloader. No "pong" received.
[ERROR  ] Things that could be wrong:
[ERROR  ]   - The bootloader is not flashed on the chip
[ERROR  ]   - The DTR/RTS lines are not working
[ERROR  ]   - The serial port being used is incorrect
[ERROR  ]   - The bootloader API has changed
[ERROR  ]   - There is a bug in this script
[ERROR  ] Could not attach to the bootloader

**Comment by bradjc** [comment]
We don't currently have tockloader support for opentitan. If you want to load apps you should look here: https://github.com/tock/tock/tree/master/boards/opentitan#programming-apps
