### ISSUE TITLE
Stale link in README

### ISSUE THREAD

**Issue by dcz-self** [tock/libtock-c#277]
The README points to the #tock IRC channel on freenode, but the channel looks completely dead.

I'm happy to hang out on #tock at libera.chat (as I do now), or set up some Matrix channel, if anyone wants to change the link. Otherwise I would suggest dropping the link altogether.

**Comment by hudson-ayers** [comment]
The Tock slack is where people mostly hang out now: https://join.slack.com/t/tockos/shared_invite/enQtNDE5ODQyNDU4NTE1LWVjNTgzMTMwYzA1NDI1MjExZjljMjFmOTMxMGIwOGJlMjk0ZTI4YzY0NTYzNWM0ZmJmZGFjYmY5MTJiMDBlOTk

**Comment by alistair23** [comment]
+1 for a Matrix channel :)
