### ISSUE TITLE
Should libtock-c require a newer elf2tab release?

### ISSUE THREAD

**Issue by brghena** [tock/libtock-c#332]
Libtock-c is still on 0.7.0, while the latest elf2tab release is 0.10.2. Is there a reason we didn't update it?

https://github.com/tock/libtock-c/blob/a715104d4733fcb4bca087a290a6c6ca46099719/Configuration.mk#L114

**Comment by ppannuto** [comment]
Yes: https://github.com/tock/libtock-c/pull/327#issuecomment-1633343681

**Comment by ppannuto** [comment]
(we need features in post-0.10.2)
