### ISSUE TITLE
Is it possible to return float or double in temperature?

### ISSUE THREAD

**Issue by HuangLiPang** [tock/libtock-c#62]
I found that the [temperature.c](https://github.com/tock/libtock-c/blob/master/libtock/temperature.c) in libtock only return int. 
Is it possible to return float or double?

**Comment by bradjc** [comment]
The value is in 1/100 degrees C, so, something like:
```c
int temp;
float temp_c = ((float) temp) / 100.0;
```
should work.

**Comment by ppannuto** [comment]
I think @bradjc has answered this, but please feel free to re-open if there's still an issue here.
